name: Continuous Integration

on:

  push:

    branches:

      - main

      - jenk
      
  pull_request:
    types:
    
      - opened
      - synchronize
      
  workflow_dispatch:

  

jobs:

  my_first_job:

    runs-on: ubuntu-latest

 

    steps:

    

    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: '17'

        distribution: 'zulu'

  

    - name: Checkout code

      uses: actions/checkout@v3
      with:
        ref: jenk
        
    - name: Create new branch
    
      run: |
          git checkout -b feature-branch
          # Make changes to the code here

    - name: Commit and push changes
      run: |
          git config --global user.email "tentacool5701@gmail.com"
          git config --global user.name "Oleksii"
          git add .
          git commit -m "Update project code in feature branch"
          git push origin feature-branch
  
    - name: Install Dependencies

      run: 'mvn compile'

 

    - name: Build application

      run: 'mvn package -DskipTests'

 

    - name: Test application

      run: 'mvn test'
