name: Continuous Integration

on:

  push:

    branches:

      - main

      - jenk
      
  pull_request:
    types:
    
      - opened
      - synchronize
      
  workflow_dispatch:

  

jobs:

  my_first_job:

    runs-on: ubuntu-latest

 

    steps:

    

    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: '17'

        distribution: 'zulu'

  

    - name: Checkout code

      uses: actions/checkout@v3
        
    - name: Clone project from jenk branch
    
      run: |
          git checkout -b feature-branch origin/jenk
          git branch # Verify that you are on the new branch

  
    - name: Install Dependencies

      run: 'mvn compile'

 

    - name: Build application

      run: 'mvn package -DskipTests'

 

    - name: Test application

      run: 'mvn test'
